services:
  api:
    depends_on:
      - clickhouse
      - nats
      - feature-extraction
      - auto-cohort
  # frontend:
  #   depends_on:
  #     - api
  # clickhouse:
  #   volumes:
  #     - ./data:/var/lib/clickhouse # volume override
