version: "3"

services:
  auto-cohort:
    build:
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file: .env
    environment:
      PYTHONUNBUFFERED: 1
    ports:
      - "3002:3002"
